### ISSUE TITLE
pander usage

### ISSUE THREAD

**Issue by daroczig** [stephenturner/annotables#1]
If you don't mind, I share some tips on how to improve the `pander` calls and make the code more readable and easier to maintain by using [global options](http://rapporter.github.io/pander/#general-options). First of all, there is no real need to call `pandoc.table`, it's totally fine to use the `pander` [general S3 method](http://rapporter.github.io/pander/#generic-pander-method) on anything.

I've seen you do not want to split the tables. For this end, you can define a global option that will be used in all future `pander` (or `pandoc.table`) calls. Eg you can set it to `100` like you did, or even to disable this feature if needed:

```r
panderOptions('table.split.table', Inf)
```

Similarly, you can set the table style as well:

```r
panderOptions('table.style', 'rmarkdown')
```

And the cell alignment can be specified too via the `table.alignment.default` option, which can be a function as well to eg justify numbers to the left and everything else to the right etc. See eg this thread on SO: http://stackoverflow.com/a/27014481/564164

Please feel free to close this ticket, I just wanted to share these (hopefully) useful tricks :)

**Comment by stephenturner** [comment]
Ah, thanks for that! I missed that in the docs when I read through them, too quickly. I had previously used `knitr::kable()` for this, but it didn't work so well with wide tables and GFMarkdown. In fact, I had to fiddle around with pander to get it to render nicely with GFM. But after having done this, pander is much more flexible than `kable()`, and I'll probably be using it from here out. Thanks again!
