### ISSUE TITLE
version 90

### ISSUE THREAD

**Issue by roryk** [stephenturner/annotables#11]
Hi Stephen,

Hope everything is going well. Ensembl released version 90 last monthish, is there a plan to update the annotations? I'm not sure what your vision was involving keeping up. Thanks so much! It is surprising how useful it is to just have the annotations on hand and not have to re-look them up every time.

**Comment by roryk** [comment]
Wow, thanks for the super fast update Stephen. This is such a nice resource.

**Comment by stephenturner** [comment]
Thanks for the push. I need to come up with a better system for
automatically building/deploying as new versions are released. With this
update I started tracking the ensembl version number in the R package
release version. If nothing else it's helpful for me to track which version
of Ensembl was used to build annotables. I'll start tagging releases also.

https://github.com/stephenturner/annotables/releases/tag/v0.1.90
