### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by lena-b** [stephenturner/annotables#15]
Hello, I am rather new to R and am not able to install the annotables package. Here is what I get:

` install.packages("devtools")
Error in install.packages : Updating loaded packages

Restarting R session...

During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
> # Use devtools to install the package
> devtools::install_github("stephenturner/annotables")
Downloading GitHub repo stephenturner/annotables@master
tar: Failed to set default locale
tar: Failed to set default locale
   During startup - Warning messages:
   1: Setting LC_CTYPE failed, using "C" 
   2: Setting LC_TIME failed, using "C" 
   3: Setting LC_MESSAGES failed, using "C" 
   4: Setting LC_MONETARY failed, using "C" 
v  checking for file '/private/var/folders/0m/_xp6xtk96v3c7nztw552_zzh0000gn/T/RtmphObqL7/remotes107e2dec0e0d/stephenturner-annotables-805a247/DESCRIPTION' ...
-  preparing 'annotables':
v  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'annotables_0.1.91.tar.gz' (2.5s)
   
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error in i.p(...) : 
  (converted from warning) installation of package '/var/folders/0m/_xp6xtk96v3c7nztw552_zzh0000gn/T//RtmphObqL7/file107e1486950e/annotables_0.1.91.tar.gz' had non-zero exit status
> library(dplyr)

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

> library(annotables)
Error in library(annotables) : there is no package called 'annotables'`

I also tried other installing methods but in the end there was never a package called 'annotables'. 
Thank you for your help!

**Comment by stephenturner** [comment]
I think this is a problem with your system. I just checked on a relatively fresh R installation and works for me. Check your locale settings in `~/.bashrc` or `~/.profile`.
