### ISSUE TITLE
Update gene->transcript tables to match mikelove/tximport#13

### ISSUE THREAD

**Issue by mdshw5** [stephenturner/annotables#2]
https://github.com/mikelove/tximport/commit/8f31541991c08ad3fe71145987ea4c4b1424ad67
mikelove/tximport#13
The `grch38_gt` data_table is useful, but could we maybe have a `grch38_tg` as well?

```
	tx	gene
1	ENST00000387314	ENSG00000210049
2	ENST00000389680	ENSG00000211459
3	ENST00000387342	ENSG00000210077
4	ENST00000387347	ENSG00000210082
5	ENST00000386347	ENSG00000209082
6	ENST00000361390	ENSG00000198888
``

**Comment by stephenturner** [comment]
I'll update. In meantime how about 

`...tx2gene=dplyr::select(grch38_gt,enstxp,ensgene)`

Stephen

**Comment by mdshw5** [comment]
Yes, absolutely what I'm using in my scripts, but I think there should be some easy way to provide the functionality in the future. Maybe just a function that returns the reversed table?

**Comment by stephenturner** [comment]
ftfy @mdshw5

**Comment by mdshw5** [comment]
Thanks - looks great!
