### ISSUE TITLE
Are grch37 and grch38 supposed to be the exact same object?

### ISSUE THREAD

**Issue by joseale2310** [stephenturner/annotables#22]
Hi, I am using the version 0.1.91 of the annotables package. I have noticed that the grch37 and grch38 objects are exactly the same.

```r
library(annotables)

identical(grch37, grch38)
```

I am surprised that even the genomic positions are exactly the same being two different versions of the human genome. Am I being stupid and missing something?

**Comment by stephenturner** [comment]
Hey @joseale2310 good catch. I haven't developed or maintained this package in years, but this is definitely a bug. Let me take a look. Hopefully the build scripts still work. Stay tuned.

**Comment by joseale2310** [comment]
Thanks for checking it out! It works now :)
