### ISSUE TITLE
Github repo webpage link redirects to weird webpage

### ISSUE THREAD

**Issue by joseale2310** [stephenturner/annotables#24]
Hi Steven,

Just one more thing that I noticed. When I click on the webpage link on this repo: www.gettinggeneticsdone.com/2015/11/annotables-convert-gene-ids.html. 

It redirects me to this weird japanese webpage:
https://earthgekinka.com/creditcardgenkinka/jibundedekiru.html

**Comment by stephenturner** [comment]
Thanks for that. I let that domain expire years ago. Link corrected, http://www.gettinggeneticsdone.blogspot.com/2015/11/annotables-convert-gene-ids.html
