### ISSUE TITLE
rename in code to add grch37

### ISSUE THREAD

**Issue by Heydt** [stephenturner/annotables#5]
Thank you for creating this package. 
I tried to add grch37 and failed.
When I run the code from your README.Rmd:

fix_genes <- . %>% 
  tbl_df %>% 
  distinct %>% 
  rename(ensgene=ensembl_gene_id,
         entrez=entrezgene,
         symbol=external_gene_name,
         chr=chromosome_name,
         start=start_position,
         end=end_position,
         biotype=gene_biotype)

myattributes <- c("ensembl_gene_id",
                  "entrezgene",
                  "external_gene_name",
                  "chromosome_name",
                  "start_position",
                  "end_position",
                  "strand",
                  "gene_biotype",
                  "description")

and adding grch37 following your code, I get:
Error in rename(., ensgene = ensembl_gene_id, entrez = entrezgene, symbol = external_gene_name,  : 
  object 'ensembl_gene_id' not found

By just removing the rename function and last pipe, everything seems to work.
I am quite new to bioinformatics, R and github. I hope 'Issues' is the right place to ask my question.

**Comment by stephenturner** [comment]
I'm guessing the `rename` you're using is probably coming from another
loaded bioconductor package. Try replacing with `dplyr::rename()` and see
if that works.

**Comment by Heydt** [comment]
Replacing it works indeed.
Thank you
